vsymfo_payment_payeer_status:
    pattern: /transaction/urlc
    defaults: { _controller: vSymfoPaymentPayeerBundle:Payment:status }

vsymfo_payment_payeer_success:
    pattern: /redirect/success
    defaults: { _controller: vSymfoPaymentPayeerBundle:Payment:success }

vsymfo_payment_payeer_fail:
    pattern: /redirect/fail
    defaults: { _controller: vSymfoPaymentPayeerBundle:Payment:fail }
